### ISSUE TITLE
Build User Interfaces by Composing CSS Utility Classes with Tailwind

### ISSUE THREAD

**Issue by zacjones93** [eggheadio-projects/egghead-tailwind#2]
##  [Build User Interfaces by Composing CSS Utility Classes with Tailwind](https://egghead.io/courses/build-user-interfaces-by-composing-css-utility-classes-with-tailwind)

Reported by user [on slack](https://eggheadio.slack.com/archives/CB287N3BQ/p1562765277037400): Not up to date(tailwind base, not tailwind preflight), some of the code on GitHub is not working as per the tutorial (card flex on large screens)

### 🛠 Setup
- Navigate to [review.egghead.io](https://review.egghead.io/)
- Start a new review
- Add course slug
- Add Dependencies
- Make a copy of this [Template](https://goo.gl/NANbTB) for review notes

### 📖 The Review
- Watch the video
- Note how code functions in video
- Check the comments
- Test the code
- Note how code functions
- Update dependencies
- Test the code
- Note how code functions
- Compare to video and pre-updated code
- Note any errors in the review app and doc
- Do not hesitate to ask any question at any time! 

### 🏆 Finished
- Navigate to the content-team slack channel
- Share your review document
- Share a snippet of the review app json output
- Add the review to your invoice 

### 💻 Copying the JSON
- hover over "items"
- click the clipboard icon
![image of copying](https://cl.ly/a8e082a72a1b/%255B30d2a1fdc29fdf4fea98725e10d63389%255D_Image%2525202019-01-10%252520at%25252012.56.16%252520PM.png)

**Comment by lsminter** [comment]
Lesson 9 isn't the same as what the instructor's video is. I've tried recreating it but whenever I add the `@variants` tag in the css file, it removed the styles that I applied to the text in my `html` file. So I believe its some issue with how I'm importing/using `tailwindcss` that isn't working. 

### index.html
```html
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>09-tailwind-extending-tailwind-with-responsive-custom-utility-classes</title>
  <link rel="stylesheet" href="./src/styles.css">
</head>

<body class="font-sans leading-normal">

  <div class="bg-gradient-blue hover:bg-gradient-orange round-lg text-white p-4 mb-2">
    <h2>Gradients...</h2>
  </div>

  <div class="bg-gradient-orange hover:bg-gradient-blue rounded-lg text-white p-4 mb-2">
    <h2>...are back!</h2>
  </div>

</body>

</html>
```

### src/styles.css
```css
@tailwind preflight;
@tailwind utilities;

@variants hover {
  .bg-gradient-blue {
    background-color: #21d4fd;
    background-image: linear-gradient(19deg, #b721ff 0%, #21d4fd 100%);
  }

  .bg-gradient-orange {
    background-color: #ffe53b;
    background-image: linear-gradient(147deg, #ff2525 0%, #ffe53b 74%);
  }
}
```
